name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: "20"

      - name: "Install Yarn"
        run: "npm install --global yarn"

      - name: "Install Node.js dependencies"
        run: "yarn install"

      - name: "Create .env file"
        run: |
          echo 'PROVIDER_URL="https://mainnet.infura.io/v3/00000000000000000000000000000000"' > .env
          echo 'PROVIDER_WSS="wss://mainnet.infura.io/ws/v3/00000000000000000000000000000000"' >> .env
          echo 'FORWARD_URL="https://relay.flashbots.net"' >> .env
          echo 'OVAL_CONFIGS="{"0x000000000000000000000000000000000000beef":{"unlockerKey":"0x000000000000000000000000000000000000000000000000000000000000beef","refundAddress":"0x000000000000000000000000000000000000beef","refundPercent":90}}"' >> .env
          echo 'AUTH_PRIVATE_KEY="0x0000000000000000000000000000000000000000000000000000000000000000"' >> .env
          echo 'MAINNET_BLOCK_OFFSET=5' >> .env

      - name: "Run the tests"
        run: "yarn test"

      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
